### PR TITLE
fix: infer - missing nullable type for non Go types

### LINKED ISSUE #41: *time.Time not translated to ["null","string"]
**Describe the bug**

When encoding a struct containing a `*time.Time` attribute, the final schema will have type `"string"` instead of `["null","string"]`. This happens because we return early when we have an [`initialSchemaMap`](https://github.com/google/jsonschema-go/blob/3ba200528d086ef03a2d8e8d4f7d7146400e342f/jsonschema/infer.go#L330-L334) match:

https://github.com/google/jsonschema-go/blob/3ba200528d086ef03a2d8e8d4f7d7146400e342f/jsonschema/infer.go#L127-L129

Bypassing the final null check:
https://github.com/google/jsonschema-go/blob/3ba200528d086ef03a2d8e8d4f7d7146400e342f/jsonschema/infer.go#L318-L321

An alternative could be declaring the standard library type when calling the `jsonschema.For` function:
```go
schema, err := jsonschema.For[example](&jsonschema.ForOptions{
	TypeSchemas: map[reflect.Type]*jsonschema.Schema{
		reflect.TypeFor[*time.Time](): {
			Types: []string{"null", "string"},
		},
	},
})
```

But because we remove the pointer [here](https://github.com/google/jsonschema-go/blob/3ba200528d086ef03a2d8e8d4f7d7146400e342f/jsonschema/infer.go#L114), we cannot differentiate a `time.Time` from a `*time.Time`.

I propose to check the `allowNull` when we have an `initialSchemaMap` match and append the `null`. The risk here is that this may also impact user-defined `TypeSchemas`, which will now have a `null` if they are a pointer (behaviour change), but I guess it should be fine?

**To Reproduce**

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/google/jsonschema-go/jsonschema"
)

type example struct {
	Value *time.Time `json:"value"`
}

func main() {
	schema, err := jsonschema.For[example](&jsonschema.ForOptions{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate JSON schema: %v", err)
		os.Exit(1)
	}
	encoded, err := json.Marshal(schema)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to encode JSON schema: %v", err)
		os.Exit(1)
	}
	fmt.Println(string(encoded))
}
```

Output:
```json
{"type":"object","required":["value"],"properties":{"value":{"type":"string"}},"additionalProperties":false}
```

**Expected behaviour**

For standard library types, I would expect the pointer to infer a `null` schema value.

**Logs**

Not required.

**Additional context**

No extra context required.

### PR DESCRIPTION
**Pull request by rafaeljusto**
When providing a struct containing an attribute wich the type is a pointer to a non-native type, the infer analysis wouldn't set the output schema type as nullable for this attribute.

Example:

```go
type example struct {
	Value *time.Time `json:"value"`
}

func main() {
	schema, err := jsonschema.For[example](&jsonschema.ForOptions{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate JSON schema: %v", err)
		os.Exit(1)
	}
	encoded, err := json.Marshal(schema)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to encode JSON schema: %v", err)
		os.Exit(1)
	}
	fmt.Println(string(encoded))
}
```

This would generate:
```json
{"type":"object","required":["value"],"properties":{"value":{"type":"string"}},"additionalProperties":false}
```

Using the `TypeSchemas` option will have the same result, since [only the element is analysed](https://github.com/google/jsonschema-go/blob/3ba200528d086ef03a2d8e8d4f7d7146400e342f/jsonschema/infer.go#L114):

```go
schema, err := jsonschema.For[example](&jsonschema.ForOptions{
	TypeSchemas: map[reflect.Type]*jsonschema.Schema{
		reflect.TypeFor[*time.Time](): {
			Types: []string{"null", "string"},
		},
	},
})
```

With this patch the null flag will be checked even when there's a match with pre-registered types, resulting on the following output:

```json
{"type":"object","required":["value"],"properties":{"value":{"type":["null","string"]}},"additionalProperties":false}
```

Resolves #41

### CODE REVIEW

File: jsonschema/infer.go [hunk 1]
```diff
@@ -125,7 +126,12 @@ func forType(t reflect.Type, seen map[reflect.Type]bool, ignore bool, schemas ma
 	}
 
 	if s := schemas[t]; s != nil {
-		return s.CloneSchemas(), nil
+		cloned := s.CloneSchemas()
+		if os.Getenv("JSONSCHEMAGODEBUG") != "typeschemasnull=1" && allowNull && s.Type != "" {
```
Comment (jba) [inline jsonschema/infer.go]: I think we should also add null to s.Types if it is populated.

Comment (jba) [inline jsonschema/infer.go]: No need to parse the environment variable, but please define a global constant with the variable name.

File: jsonschema/infer_test.go [hunk 2]
```diff
@@ -224,6 +227,7 @@ func TestForType(t *testing.T) {
 		I int
 		F func()
 		C custom
+		P *custom
```
Comment (jba) [inline jsonschema/infer_test.go]: Make this `**custom` just to test that case.

**Comment by rafaeljusto** [comment]
Thanks for the feedback @jba ! Let me know if I need to apply further changes. 🙂
