### PR TITLE
fix: infer - arrays should always accept null

### LINKED ISSUE #48: Allow `null` for arrays
**Describe the bug**

In Go, any slice attribute can store `nil` instead of an allocated value.

https://github.com/google/jsonschema-go/blob/2196fedd778dfb94094da888f59e631b4d3f3992/jsonschema/infer.go#L219

Here, it always sets the type as `array`, where I think it should be `["null","array"]`.

**To Reproduce**

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/google/jsonschema-go/jsonschema"
)

func main() {
	schema, err := jsonschema.For[[]int64](&jsonschema.ForOptions{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate JSON schema: %v", err)
		os.Exit(1)
	}
	encoded, err := json.Marshal(schema)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to encode JSON schema: %v", err)
		os.Exit(1)
	}
	fmt.Println(string(encoded))
}
```

Output:
```json
{"type":"array","items":{"type":"integer"}}
```

**Expected behavior**
All slices should allow the `null` type:
```json
{"type":["null","array"],"items":{"type":"integer"}}
```

**Logs**
Not required.

**Additional context**
No extra context required.

### PR DESCRIPTION
**Pull request by rafaeljusto**
When building the JSON schema for an array we should always allow "null" since any slice in Go can contain a `nil` value.

Resolves #48

### CODE REVIEW

File: jsonschema/validate_test.go [hunk 1]
```diff
@@ -494,7 +494,7 @@ func TestStructEmbedding(t *testing.T) {
 			name:       "ExportedPointer",
 			targetType: reflect.TypeOf([]Banana{}),
 			wantSchema: &Schema{
-				Type: "array",
+				Types: []string{"null", "array"},
```
Comment (jba) [inline jsonschema/validate_test.go]: Call this test case "slice" and add one for an actual array.

File: jsonschema/doc.go [hunk 2]
```diff
@@ -91,6 +91,20 @@ implementations. See [learnjsonschema.com] for more recommendations about "forma
 The content keywords described in [section 8 of the validation spec]
 are recorded in the schema, but ignored during validation.
 
+# Controlling behavior changes
+
+Minor and patch releases of this package may introduce behavior changes as part
+of bug fixes or correctness improvements. To help manage the impact of such
+changes, the package allows you to lock in specific behaviors using the
```
Comment (jba) [inline jsonschema/doc.go]: s/lock in specific behaviors/access previous behaviors/

**Review by jba — CHANGES_REQUESTED** [review]

**Comment by rafaeljusto** [comment]
Thanks for taking the time to review this and share your feedback, @jba! I’ve applied your suggestion. Let me know if anything else needs adjusting.

**Review by jba — APPROVED** [review]
Sorry for the delay.
